In [1]:
import torch , gc

In [2]:
print(torch.__version__)

2.5.1


### tensor

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
# get dimation of tensor 
scalar.ndim

0

In [5]:
# to get item in tensor
scalar.item()

7

In [6]:
#vector
vector = torch.tensor([7,7])
print(vector , vector.ndim , vector.shape)

tensor([7, 7]) 1 torch.Size([2])


In [7]:
#MATRIX
MATRIX = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(MATRIX , MATRIX.ndim , MATRIX.shape)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) 2 torch.Size([3, 3])


In [8]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(TENSOR , TENSOR.ndim , TENSOR.shape)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]]) 3 torch.Size([2, 2, 3])


### Random tensor

In [9]:
random_tensor = torch.rand(size=(3,4))
random_tensor

tensor([[0.5205, 0.7899, 0.6388, 0.1876],
        [0.4873, 0.5705, 0.0810, 0.3388],
        [0.2571, 0.1196, 0.5010, 0.4714]])

In [10]:
random_image_size_tensor = torch.rand(3,224,224)
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [11]:
#zero tensor

zero_tensor = torch.zeros(size=(3,4))
zero_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [12]:
one_tensor = torch.ones(size=(3,4), dtype=torch.int8)
one_tensor

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int8)

In [13]:
one_tensor.dtype

torch.int8

In [14]:
## create range of tensor 

range_tensor = torch.arange(start=0,end=10,step=1).reshape(2,5)
range_tensor

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [15]:
## tensor dtypes

int_8_tensor = torch.tensor([1,2,3], dtype=torch.int8)
int_32_tensor = torch.tensor([1,2,3], dtype=torch.int32)
float_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)
bool_tensor = torch.tensor([1,0,1], dtype=torch.bool)
int_8_tensor, int_32_tensor, float_tensor, bool_tensor

(tensor([1, 2, 3], dtype=torch.int8),
 tensor([1, 2, 3], dtype=torch.int32),
 tensor([1., 2., 3.]),
 tensor([ True, False,  True]))

In [16]:
## reshaping, stacking, squeezing, unsqueezing tensors
x = torch.arange(1,10)
x , x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [17]:
x = x.reshape(1,3,3)

In [18]:
x , x.view(3,3) # view share memory of original tensor

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]))

In [19]:
x = x.reshape(1,3,3)

In [20]:
# pytorch with numpy
import numpy as np

In [21]:
x = np.arange(1.,10.)

In [22]:
x.dtype

dtype('float64')

In [23]:
x_torch = torch.from_numpy(x)

In [24]:
x_torch

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)

In [25]:
# running tensor on GPU on CUDA
!nvidia-smi

Sat Aug 30 09:11:11 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 575.64.03              Driver Version: 575.64.03      CUDA Version: 12.9     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4050 ...    Off |   00000000:01:00.0 Off |                  N/A |
| N/A   45C    P8              2W /   60W |      15MiB /   6141MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [26]:
torch.cuda.is_available()

True

In [27]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [28]:
## count of gpu
torch.cuda.device_count()

1

In [29]:
# Create a tensor on CPU

tensor = torch.tensor([1,2,3])

tensor , tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [30]:
# create a tensor on GPU
tensor = torch.tensor([1,2,3],device=device)

print(tensor , tensor.device)

#also you can do like this

tensor_to_gpu = tensor.to(device)
print(tensor_to_gpu , tensor_to_gpu.device)

tensor([1, 2, 3], device='cuda:0') cuda:0
tensor([1, 2, 3], device='cuda:0') cuda:0


In [31]:
# moving back to cpu
tensor_to_cpu = tensor_to_gpu.to("cpu")
print(tensor_to_cpu , tensor_to_cpu.device)

tensor([1, 2, 3]) cpu


In [32]:
# we can't convert gpu tensor directly to numpy
tensor_to_gpu.numpy() # we get error

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [33]:
# how to free up memory
del tensor_to_gpu
torch.cuda.empty_cache()
# tensor_to_gpu