In [4]:
import tensorflow as tf

In [5]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [6]:
tensor_one_d = tf.constant([2,0,-3,8,90])
print(tensor_one_d)

tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int32)


In [7]:
tensor_two_d = tf.constant([[1,2,0],[3,5,-1],[1,5,6],[2,3,8]])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [8]:
tensor_three_d = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(tensor_three_d)

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


In [6]:
tensor_four_d = tf.constant([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]],[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]])
print(tensor_four_d)

tf.Tensor(
[[[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]


 [[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]], shape=(2, 2, 2, 2), dtype=int32)


In [7]:
#shape method of tensor return dimantion of tensor
#tensor is multidimation array
print(tensor_zero_d.shape)
print(tensor_one_d.shape)
print(tensor_two_d.shape)
print(tensor_three_d.shape)
print(tensor_four_d.shape)


()
(5,)
(4, 3)
(2, 2, 2)
(2, 2, 2, 2)


In [8]:
#type casting
tensor_one_d = tf.constant([2,0,-3,8,90.])
print(tensor_one_d)
casted_one_d = tf.cast(tensor_one_d,dtype=tf.int16)
print(casted_one_d)


tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)
tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int16)


In [9]:
#boolen
tensor_bool = tf.constant([True,True,False,True])
print(tensor_bool)
tensor_bool_num = tf.constant([1,1,0,1])
casted_tensor_bool = tf.cast(tensor_bool_num,dtype=tf.bool)
print(casted_tensor_bool)


tf.Tensor([ True  True False  True], shape=(4,), dtype=bool)
tf.Tensor([ True  True False  True], shape=(4,), dtype=bool)


In [10]:
#string
tensor_string = tf.constant("hello world")
print(tensor_string)
tensor_one_d_string = tf.constant(["hello","world"])
print(tensor_one_d_string)

tf.Tensor(b'hello world', shape=(), dtype=string)
tf.Tensor([b'hello' b'world'], shape=(2,), dtype=string)


In [11]:
#convert np array into tensor
import numpy as np
np_array = np.array([1,2,3])

converted_np_array = tf.convert_to_tensor(np_array)
print(converted_np_array)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [12]:
# make identity matrix
eye_matrix = tf.eye(num_rows=3,dtype=tf.int8 , num_columns=None,batch_shape=[2,2,])
print(eye_matrix)
print()
print(5*eye_matrix)

tf.Tensor(
[[[[1 0 0]
   [0 1 0]
   [0 0 1]]

  [[1 0 0]
   [0 1 0]
   [0 0 1]]]


 [[[1 0 0]
   [0 1 0]
   [0 0 1]]

  [[1 0 0]
   [0 1 0]
   [0 0 1]]]], shape=(2, 2, 3, 3), dtype=int8)

tf.Tensor(
[[[[5 0 0]
   [0 5 0]
   [0 0 5]]

  [[5 0 0]
   [0 5 0]
   [0 0 5]]]


 [[[5 0 0]
   [0 5 0]
   [0 0 5]]

  [[5 0 0]
   [0 5 0]
   [0 0 5]]]], shape=(2, 2, 3, 3), dtype=int8)


In [13]:
#make array where every element is same 

fill_tensor = tf.fill([3,4],5,None)
print(fill_tensor)

tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)


In [14]:
#also same all element is 1 
ones_tensor = tf.ones([3,4])
print(ones_tensor)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)


In [15]:
all_ones = tf.ones_like(tensor_two_d)
print(all_ones)

tf.Tensor(
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]], shape=(4, 3), dtype=int32)


In [18]:
#zero tensor
zero_tensor = tf.zeros([3,4], dtype=tf.int16)
print(zero_tensor)

tf.Tensor(
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]], shape=(3, 4), dtype=int16)
